version: "3.3"

services:
  elasticsearch:
    build: ./elastisearch-opendistro-sec
    image: sergbs/elastic:1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      # - elasticsearch-vol:/usr/share/elasticsearch/data 
      - ./elastisearch-opendistro-sec/config.yml:/opt/bitnami/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
      - ./elastisearch-opendistro-sec/roles_mapping.yml:/opt/bitnami/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-network
    depends_on:
      - openldap
  kibana:
    build: ./kibana-opendistro-sec
    image: sergbs/kibana:1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - ./kibana-opendistro-sec/kibana.yml:/bitnami/kibana/conf/kibana.yml
    networks:
      - elastic-network
  openldap:
    image: osixia/openldap
    container_name: openldap
    command: --copy-service
    volumes:
      - config:/etc/ldap/slapd.d
      - database:/var/lib/ldap
    ports:
      - "389:389"
      - "636:636"
      - "8389:389"
    environment:
      - "LDAP_TLS=false"
    networks:
      - elastic-network
  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    links:
      - openldap
    depends_on:
      - openldap
    ports:
      - "6443:443" 
    networks:
      - elastic-network

volumes:
  elasticsearch-vol:
  config:
  database:

networks:
  elastic-network: