_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      ldap:
        http_enabled: true
        transport_enabled: false
        order: 2
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: ldap
          config:
            # disabled only for demo showcase NOT FOR PRODUCTION
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: false
            hosts:
              - openldap:389
            bind_dn: cn=admin,dc=example,dc=org
            password: admin
            userbase: 'dc=example,dc=org'
            usersearch: '(cn={0})'
            username_attribute: cn
    authz:
      roles_from_myldap:
        http_enabled: true
        transport_enabled: false
        authorization_backend:
          type: ldap
          config:
            # disabled only for demo showcase NOT FOR PRODUCTION
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: false
            hosts:
              - openldap:389
            bind_dn: cn=admin,dc=example,dc=org
            password: admin
            rolebase: 'dc=example,dc=org'
            rolesearch: '(cn={0})'
            userroleattribute: null
            userrolename: disabled
            rolename: cn
            resolve_nested_roles: true
            userbase: 'dc=example,dc=org'
            usersearch: '(cn={0})'
